services:
  todo-ui:
    container_name: 'todo-ui'
    image: 'todo-ui-image'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:3000
    networks:
      - base-network

networks:
  base-network:
    external: true